douwed/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from douwed.views import *
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'', include('social_auth.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^reg/$', reg),
                       url(r'^logout/$', logout),
                       url(r'^$', index),
                       url(r'^about/$', about),
                       url(r'^get-user-info/$', get_user_info),
                       url(r'^people/([1-9]\d{6,7})/$', people_info),
                       url(r'^mine/$', mine),
                       url(r'^sorry/$', sorry),
                       url(r'^random/$', random),
                       url(r'^page/(\d)$', page),
                       )

info/models.py
from django.db import models
from django.contrib.auth.models import User
from social_auth.fields import JSONField


class UserDetail(models.Model):
    user = models.OneToOneField(User)
    user_name = models.TextField()
    uid = models.CharField(max_length=20)
    head_img = models.URLField(max_length=100)
    want_say = models.CharField(max_length=9999)
    position = models.TextField(blank=True, null=True)
    show = models.BooleanField(default=False)
    extra = JSONField(default='{}')

    def __unicode__(self):
        return self.user_name

from django.db.models.signals import post_save


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserDetail.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

info/forms.py
from django import forms


class ContactForm(forms.Form):
    position = forms.CharField(max_length=15, required=False)
    want_say = forms.CharField(widget=forms.Textarea, max_length=5000)

douwed/views.py
# coding=utf-8
import sys
default_encoding = 'utf-8'
if sys.getdefaultencoding() != default_encoding:
    reload(sys)
    sys.setdefaultencoding(default_encoding)


from django.shortcuts import render_to_response, get_object_or_404
from info.forms import ContactForm
from info.models import UserDetail
from django.template import RequestContext
from social_auth.models import UserSocialAuth
from django.http import HttpResponseRedirect, Http404
from django.contrib import auth
import json
import urllib2
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def sorry(request):
    if not request.user.is_authenticated():
        return render_to_response("sorry.html", RequestContext(request, {}))
    return HttpResponseRedirect("/")


def index(request):
    saysList = UserDetail.objects.filter(show=1).order_by('-id')
    userdetail = {}
    title = "豆伴"
    if request.user.username:
        id = request.user.id
        userdetail = get_object_or_404(UserDetail, user_id=id)
    return render_to_response("index.html", RequestContext(request, {'title': title, 'userdetail': userdetail, 'saysList': saysList}))


def page(request, offset):
    saysList = UserDetail.objects.filter(show=1).order_by('-id')
    paginator = Paginator(saysList, 6)
    try:
        contacts = paginator.page(offset)
    except PageNotAnInteger:
        raise Http404()
    except EmptyPage:
        raise Http404()
    saysList = contacts.object_list
    title = "豆伴"
    userdetail = {}
    if request.user.username:
        id = request.user.id
        userdetail = get_object_or_404(UserDetail, user_id=id)
    return render_to_response("index.html", RequestContext(request, {'title': title, 'userdetail': userdetail, 'saysList': saysList, 'contacts': contacts, }))


@login_required
def random(request):
    who = UserDetail.objects.filter(show=1).order_by('?')[0]
    return HttpResponseRedirect('/people/' + who.uid)


def about(request):
    id = request.user.id
    userdetail = get_object_or_404(UserDetail, user_id=id)
    return render_to_response("about.html", RequestContext(request, {"userdetail": userdetail}))


@login_required
def reg(request):
    form = ContactForm()
    errors = []
    id = request.user.id
    userdetail = get_object_or_404(UserDetail, user_id=id)
    if request.method == 'POST':
        if not request.POST['position']:
            errors.append('请输入一个地址')
        if not request.POST['want_say']:
            errors.append('请输入你想对你另一半说的话')
        if not errors:
            userdetail.position = request.POST['position']
            userdetail.want_say = request.POST['want_say']
            userdetail.show = True
            userdetail.save()
            return HttpResponseRedirect('/get-user-info/')
    title = "在豆伴登记"
    return render_to_response("reg.html",
                              RequestContext(request, {'form': form, 'errors': errors, 'title': title, 'userdetail': userdetail}))


@login_required
def logout(request):
    auth.logout(request)
    return render_to_response("logout.html")


def getJson(inUrl, num=0):
    returnData = ""
    try:
        returnData = urllib2.urlopen("https://api.douban.com/v2/user/" + inUrl, timeout=1).read()
    except urllib2.URLError:
        num = num + 1
        if (num < 3):
            returnData = getJson(inUrl, num)
    return returnData


@login_required
def get_user_info(request):
    if request.method == 'GET':
        id = request.user.id
        userdetail = get_object_or_404(UserDetail, user_id=id)
        social_auth = get_object_or_404(UserSocialAuth, user=id)
        userdetail.uid = social_auth.uid
        userdetail.head_img = 'http://img1.douban.com/icon/u' + userdetail.uid + '.jpg'
        userdetail.extra = social_auth.extra_data
        resUser = getJson(userdetail.uid)
        jsonVal = json.loads(resUser)
        userdetail.user_name = jsonVal["name"]
        userdetail.head_img = jsonVal["avatar"]
        userdetail.save()
    return HttpResponseRedirect('/mine')


def people_info(request, offset):
    try:
        offset = int(offset)
    except ValueError:
        raise Http404()
    saysList = get_object_or_404(UserDetail, uid=offset)
    if not saysList.uid:
        raise Http404()
    if not saysList.position:
        raise Http404()
    userdetail = {}
    title = saysList.user_name + " - 豆伴"
    if request.user.username:
        id = request.user.id
        userdetail = get_object_or_404(UserDetail, user_id=id)
    return render_to_response("people.html", RequestContext(request, {'title': title, 'userdetail': userdetail, 'saysList': saysList}))


@login_required
def mine(request):
    id = request.user.id
    userdetail = get_object_or_404(UserDetail, user_id=id)
    return HttpResponseRedirect('/people/' + userdetail.uid)

info/views.py
# Create your views here.

templates/about.html
你好, 欢迎来到豆伴, 祝福你找到属于自己的另一半. <br />
--From yhben & phoenix

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
    
    <head>
        <meta http-equiv="content-type" content="text/html;charset=utf-8">
        <title>
            {{ title }}
        </title>
        <meta content="width=device-width,initial-scale=1" name="viewport">
        <meta name="baidu-site-verification" content="zOQSNgmAoLpOVo8c" />
        <script type="text/javascript">
                        function retun_to() {
                    if (RegExp("^http://www.").test(location.href)) {
                        window.location = location.href.replace(/^http:\/\/www./, "http://");
                    }
                };
                retun_to()
        </script>
        <link rel="stylesheet" href="/static/css/bootstrap.css">
        <link rel="stylesheet" href="/static/css/style.css">
        <link href='http://fonts.googleapis.com/css?family=Spirax' rel='stylesheet'
        type='text/css'>
        <script src="http://lib.sinaapp.com/js/jquery/1.9.1/jquery-1.9.1.min.js"
        type="text/javascript">
                                                                                                                                                                                        
        </script>
        <script src="/static/js/bootstrap.min.js" type="text/javascript">
                                                                                                                                                                                        
        </script>
        <script type="text/javascript">
                                                                                          var _gaq = _gaq || [];
                                                                                  _gaq.push(['_setAccount', 'UA-35427335-1']);
                                                                                  _gaq.push(['_trackPageview']);

                                                                                  (function() {
                                                                                      var ga = document.createElement('script');
                                                                                      ga.type = 'text/javascript';
                                                                                      ga.async = true;
                                                                                      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                                                                                      var s = document.getElementsByTagName('script')[0];
                                                                                      s.parentNode.insertBefore(ga, s);
                                                                                  })();
        </script>
        <!--[if lt IE 9]><div style="position:fixed;top:0;left:0;right:0;bottom:0;background:black;z-index:999999999;text-align:center;"><a href="http://www.llavie.com/godarkforie-cn/"><img src="http://www.llavie.com/godarkforie-cn/img/zh-cn.jpg" alt="您正在使用旧版本的Internet Explorer浏览器" /></a></div><![endif]-->
    </head>
    
    <body onbeforeonload="return_to()">
        <div class="navbar navbar-static-top">
            <div class="navbar-inner">
                <div class="container">
                    <a href="/" class="navbar-brand">Douwed</a>
                    <div class="nav-collapse">
                        <ul class="nav pull-right" id="login">
                            {% if user.is_authenticated%}
                            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{userdetail.head_img}}" class="img-circle">{{userdetail.user_name}}<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="/reg">{% if userdetail.want_say %}<i class="icon-edit"></i>修改登记资料</a>
                                    </li>
                                    <li>
                                        <a href="/mine"><i class="icon-user"></i>我的主页</a>
                                    </li>
                                    {% else %}
                                    <i class="icon-plus-sign">
                                    </i>
                                    在豆伴登记{% endif %}
                                    </a></li><li><a class="random visible-phone" href="/random"><i class="icon-random"></i>随机</a></li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="/logout"><i class="icon-signout"></i>登出</a>
                            </li>
                            </ul>
                            </li>
                            {% else %}
                            <i class="icon-signin">
                            </i>
                            <a href=" {% url socialauth_begin 'douban2' %}"><img src="http://img3.douban.com/pics/douban-icons/favicon_24x24.png" alt="使用豆瓣登陆"></a>
                            {% endif %}
                        </ul>
                    </div>
                    <button type="button" class="navbar-toggle pull-right" data-toggle="collapse"
                    data-target=".nav-collapse">
                        <span class="icon-bar">
                        </span>
                        <span class="icon-bar">
                        </span>
                        <span class="icon-bar">
                        </span>
                    </button>
                    <div class="nav-collapse collapse">
                        <ul class="nav hidden-phone">
                            <li><a class="home" href="/"><i class="icon-home"></i>首页</a></li>
                            <li>
                                <a class="random" href="/random"><i class="icon-random"></i>随机</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% block content %}{% endblock %}
        <footer>
            <div class="container">
                <div class="row">
                    <div class="span10 push1">
                        <hr />
                    </div>
                    <div class="span6 pull-right text-right">
                        <a href="/about"><i class="icon-info-sign"></i>关于</a>
                        <a href="http://ow.douwed.com"><i class="icon-leaf"></i>博客</a>
                    </div>
                    <div class="span6 pull-left">
                        2013 Copyright © www.douwed.com
                    </div>
                </div>
            </div>
        </footer>
    </body>

</html>

templates/index.html
{% extends "base.html" %} {% block content %}
<div class="row">
    {% for user in saysList %}{%if user.uid and user.want_say %}
    <div class="span8 push2" id="main">
        <div class="span10 push1">
            {{user.want_say|escape|linebreaks|slice:"800"}}{%if user.want_say|length >= 800%}......
            <br />
            <p class="text-center"><a href="/people/{{user.uid}}/">查看全部</a></p>{%endif%}
            <hr />
            <div class="row-fluid text-center">
                <div id="author" class="span4 push4 text-center">
                    <a href="/people/{{user.uid}}/"><img class="img-circle" src="{{user.head_img}}" alt="{{user.user_name}}"></a>
                    <br />
                    <a href="/people/{{user.uid}}/">{{user.user_name}}</a>
                </div>
            </div>
        </div>
    </div>
    {% endif%}{% endfor %}
</div>
{%if contacts.number%}

<div class="span8 push2 text-center">
        <ul class="pager">
            {% if contacts.has_previous %}
            <li class="previous"><a href="{{ contacts.previous_page_number }}"><i class="icon-arrow-left"></i></a></li>
            {% else %}
            <li class="previous disabled"><a><i class="icon-arrow-left"></i></a></li>
            {%endif%}
            <li><a>{{ contacts.number }}/{{ contacts.paginator.num_pages }}</a></li>
            {% if contacts.has_next %}
            <li class="next"><a href="{{ contacts.next_page_number }}"><i class="icon-arrow-right"></i></a></li>
            {%else%}
            <li class="next disabled"><a><i class="icon-arrow-right"></i></a></li>
            {% endif %}
        </ul>
</div>
{%endif%}

{% endblock %}

templates/logout.html
<b>您已经成功的退出了</b>
<script>window.location = "http://douwed.com";</script>

templates/people.html
{% extends "base.html" %} {% block content %}
<div class="row">
    {% if saysList.want_say %}
    <div class="span8 push2" id="main">
        <div class="span10 push1">
            {{saysList.want_say|escape|linebreaks}}
            <hr />
            <div class="row-fluid text-center">
                <div id="author" class="span4 push4 text-center">
                    <a href="http://www.douban.com/people/{{saysList.uid}}/"><img src="{{saysList.head_img}}" alt="{{saysList.user_name}}"></a>
                    <br />
                    <a href="http://www.douban.com/people/{{saysList.uid}}/">{{saysList.user_name}}的豆瓣<small><i class="icon-external-link"></i></small></a>
                    <br />
                </div>
            </div>
        </div>
    </div>
    <div class="span8 push2 text-center hidden-phone" id="main">
        <div class="row-fluid">
            <button type="button" class="btn btn-info" id="showmore">
                显示ta的读书信息
            </button>
            <script>$("#showmore").click(function() {$("#doubanj").slideToggle()});
            </script>
            <hr />
            <div id="doubanj">
            </div>
            <!-- <iframe id="doubanj" frameborder="0" marginwidth="1%" src="http://www.doubanj.com/people/{{saysList.uid}}/"
            height="500px" width="100%"></iframe> -->
            <script>
            var iframe = document.createElement("iframe");
iframe.src = "http://www.doubanj.com/people/{{saysList.uid}}/";
iframe.frameBorder = 0;
iframe.height = "500px";
iframe.width = "100%";

if (iframe.attachEvent) {
    iframe.attachEvent("onload", function() {
        $("#doubanj").hide();
    });
} else {
    iframe.onload = function() {
        $("#doubanj").hide();
    };
}

document.getElementById("doubanj").appendChild(iframe);
            </script>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/reg.html
{% extends "base.html" %}{% block content %}
<div class="row">
    <div class="span8 push2" id="main">
        <form class="form-signin text-center" action="" method="post">
            <h2 class="form-signin-heading">
                在豆伴登记
            </h2>
            {% if errors %}
            <ul>
                {% for error in errors %}
                <li>
                    {{ error }}
                </li>
                {% endfor %}
            </ul>
            {% endif %} {% csrf_token %}
            <p>
                <input id="id_position" type="text" name="position" maxlength="15" placeholder="请输入你的地址  必填"
                value="{{userdetail.position}}">
            </p>
            <p>
                <textarea rows="15" id="id_want_say" name="want_say" placeholder="请输入你想要说的话  必填">{% if userdetail.position %}{{userdetail.want_say}}{%endif%}</textarea>
            </p>
            <p>
            </p>
            <button class="btn btn-large btn-primary" type="submit">
                确认
            </button>
        </form>
    </div>
</div>
{%endblock%}

templates/sorry.html
<!DOCTYPE html>
<html lang="zh-CN">
    
    <head>
        <meta http-equiv="content-type" content="text/html;charset=utf-8">
        <title>
            这个页面需要你登入才能查看
        </title>
        <style>
            body {background: url(http://ww1.sinaimg.cn/large/bfadf3bejw1e2zn23i4rtj.jpg)
            no-repeat center center fixed; -moz-background-size: cover; background-size:
            cover;} .welcome{font-weight: 300; line-height: 22px; color: #EEE; text-shadow:
            #000 0 1px 2px;font-family: 'Helvetica Neue', Arial, sans-serif;font-size:
            1.3em;} h1{font-size: 2em; font-weight: bold;text-rendering: optimizeLegibility;}.douban{font-family:Lucida,Verdana,Hiragino Sans GB,WenQuanYi Micro Hei,sans-serif;
}
a.click {
color: #060;
background-color: #E4F2E4;
border: 0.06em solid #071;
padding: 0.333em 0.222em 0.222em 0.333em;
font-size: 1.125em;
text-decoration: none;
border-top-right-radius: 0.1666em;
border-bottom-right-radius: 0.1666em;
}
body{background-color:white}
a.dou {
color: #FFF;
background-color: #071;
border: 0.042em solid #071;
padding: 0px 0 0.125em 0.125em;
font-size: 1.5em;
text-decoration: none;
border-top-left-radius: 0.125em;
border-bottom-left-radius: 0.125em;
}
        </style>
        <script type="text/javascript">
                                        function retun_to() {
                                    if (RegExp("^http://www.").test(location.href)) {
                                        window.location = location.href.replace(/^http:\/\/www./, "http://");
                                    }
                                };
                                retun_to();
        </script>
        <script type="text/javascript">
                                                var _gaq = _gaq || [];
                                        _gaq.push(['_setAccount', 'UA-35427335-1']);
                                        _gaq.push(['_trackPageview']);

                                        (function() {
                                            var ga = document.createElement('script');
                                            ga.type = 'text/javascript';
                                            ga.async = true;
                                            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                                            var s = document.getElementsByTagName('script')[0];
                                            s.parentNode.insertBefore(ga, s);
                                        })();
        </script>
    </head>
    
    <body onbeforeonload="return_to()">
        <div class="login">
            <div class="welcome">
            <h1>
                欢迎来到 Douwed。
            </h1>
            <p>
                在这里，找到生命中的另一半。
            </p>
        </div>
            <div class="douban">
                <a href="{% url socialauth_begin 'douban2' %}" class="dou">豆</a><a class="click" href="{% url socialauth_begin 'douban2' %}">用豆瓣账号登入</a>
            </div>
        </div>
    </body>

</html>